[package]
name = "proj-struct-rust"
version = "0.1.0"
authors = ["Erich Schroeter <erich.schroeter@gmail.com>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }
